name: godot-check

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Godot
        uses: firebelley/setup-godot@v1
        with:
          version: '4.4.1'
          use-dotnet: false

      - name: Run headless check
        run: |
          godot --headless --check-only --path .

      - name: Quick boot (1 frame)
        run: |
          godot --headless --quit-after 1 --path .

